<?php

namespace AppBundle\Repository;

//use AppBundle\Entity\TurnoPars;

/**
 * CentroIntegralRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CentroIntegralRepository extends \Doctrine\ORM\EntityRepository
{

	//obtengo los turnos para la sucursal $id_ci, fecha y hora seleccionada
	public function findAllTurnos($id_ci, $fecha, $hora)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT tp FROM AppBundle:CentroIntegral ci JOIN AppBundle:TurnoPar tp
                	WHERE 
                		tp.centrointegral   = :id_ci AND
                		tp.fecha 			= :fecha AND
                		tp.hora  			= :hora 
                	'
            )->setParameters( array( 
            		'id_ci' => $id_ci,
            		'fecha' => $fecha,
            		'hora'  => $hora
            		)
            )
            ->getResult();
    }

    //obtengo centros integrales de acuerdo a la fecha y hora seleccionado
    public function findCIporTurno($fecha, $hora)
    {
    	return 'hola';
    }

}