<?php

namespace AppBundle\Repository;

/**
 * FlotaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FlotaRepository extends \Doctrine\ORM\EntityRepository
{
}
