<?php

namespace AppBundle\Repository;

/**
 * OperarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class OperarioRepository extends \Doctrine\ORM\EntityRepository
{
}
