<?php

namespace AppBundle\Repository;

/**
 * TurnoParRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TurnoParRepository extends \Doctrine\ORM\EntityRepository
{
}
