<?php

namespace AppBundle\Repository;

/**
 * VehiculoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class VehiculoRepository extends \Doctrine\ORM\EntityRepository
{

	public function findPrecioVehiculo($vehiculo)
    {
        return $this->getEntityManager()
            ->createQuery(
                'SELECT v.precio FROM AppBundle:Vehiculo v WHERE v.id = $vehiculo'
            )
            ->getResult();
    }
}
